name: Build release

on:
  push:
    branches:
      - 'master'

jobs:
  determine_tag:
    name: Determine tag
    runs-on: ubuntu-latest
    outputs: 
      version: ${{ steps.tag_version.outputs.version }}
      version_tag: ${{ steps.tag_version.outputs.version_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          filter: blob:none # exclude file contents for faster checkout
      - name: Get current date
        id: date
        run: echo "date=$(date +'%m%d%H%M')" >> $GITHUB_OUTPUT
      - name: Get short commit hash
        id: sha_short
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Determine tag
        id: tag_version
        uses: PaulHatch/semantic-version@v6.0.2
        env:
          VERSION_STABLE: "${major}.${minor}.${patch}"
          VERSION_PRERELEASE: "${major}.${minor}.${patch}-pre-${increment}-${{ steps.date.outputs.date }}"
        with:
          tag_prefix: ""
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          version_format: "${{ (github.event_name == 'release' && env.VERSION_STABLE) || env.VERSION_PRERELEASE }}"
          bump_each_commit: false
          search_commit_body: false

  docker_build:
    name: Build Docker image(s)
    needs: [determine_tag]
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm64,riscv64,arm
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/riscv64
      - name: Build Docker image(s)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/riscv64
          push: false
          build-args: |
            VERSION=${{ needs.determine_tag.outputs.version }}
          tags: |
            opvolger/knock:${{ needs.determine_tag.outputs.version }}
          outputs: type=local,dest=./output
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ./output/knock-${{ needs.determine_tag.outputs.version }}-amd64.tar.gz
          archive: false
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ./output/knock-${{ needs.determine_tag.outputs.version }}-arm64.tar.gz
          archive: false
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ./output/knock-${{ needs.determine_tag.outputs.version }}-armv7.tar.gz
          archive: false
      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: ./output/knock-${{ needs.determine_tag.outputs.version }}-riscv64.tar.gz
          archive: false
